feat: Add inherit property
quanxiang-cloud/one-for-all pull request #10
Opened 2022-03-08 04:25 UTC by EliChen95

# Add inherit property
add property type `inherit_property`
find parent node by `parentIndex` 
set current node prop value equal to parent'prop

2022-03-08 06:22 UTC, markduan requested changes

2022-03-08 06:22 UTC, markduan commented on packages/schema-spec/src/index.d.ts
> +    type: 'inherit_property';
使用 `inherited`, 形容词形式吧

2022-03-08 06:22 UTC, markduan commented on packages/schema-spec/src/index.d.ts
> +    convertor: StateConvertExpression | StateConvertorFuncSpec;
convertor 应该是可选的

2022-03-08 06:22 UTC, markduan commented on packages/render-engine/src/deserialize/parse-inherit-property.ts
> +export default function parseInheritProperty(
你看这样是不是实现更简单：

- 初始化一个 string `Set`
- 遍历 schema 中的各个节点，记录当前节点的完整 id 路径
- 当遇到有 `inherit_property` 的节点时，从当前节点的路径中取出被 inherited 的 node ID
- 将上面的 node id 存入最开始初始化的 Set 中
- 返回 Set, 使用 Set 初始化 NodePropsCache

2022-03-08 06:22 UTC, markduan commented on packages/render-engine/src/use-instantiate-props/index.ts
> +      if(ctx.nodePropsCache.hasCacheKey(`${nodeID}.${key}`)) {
- 缓存不用分 property，字节点在使用时也是把 parent props 当成整体用
- 缓存时需要过滤掉 functional property
-  `ctx.nodePropsCache.hasCacheKey` 这部分判断可以集成到 nodePropsCache 中

2022-03-08 06:22 UTC, markduan commented on packages/render-engine/src/use-instantiate-props/index.ts
> +        ctx.nodePropsCache.setProps(`${nodeID}.${key}`, prop);
存的时候，key 应该是当前 node 的完整 path 吧

2022-03-24 03:09 UTC, markduan requested changes

2022-03-24 03:09 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +  addCacheID(nodeID: string): void {
这个方法没用吧？

2022-03-24 03:09 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +  cache: Record<string, BehaviorSubject<unknown>>;
cache 的 props 值类型应该是 `Record<string, unknown>`, props 始终是对象

2022-03-24 03:09 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +  clearProps(path: string): void {
这个方法也没用吧？

2022-03-24 03:09 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +const NODE_SHOULD_NOT_CACHE: SchemaNode['id'][] = ['dummyLoopContainer', 'placeholder-node'];
'dummyLoopContainer', 'placeholder-node' 不应该出现在最终渲染的 dom tree 里，这里不用做判断。如果出现了，那是 bug。

我刚看了一下代码，看上去是不会渲染到 dom tree 的，还没测试过。

2022-03-24 03:09 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +    const nodePath = convertPath(path).split('/');
convertPath 这个方法只在这里用到吧，那不应该放到 use-instantiate-props/utils。另外这个方法的名称意思比较模糊，其实可以将 33 和 34 合并到一个方法里

2022-03-24 03:09 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +  hasCacheID(nodeID: string): boolean {
hasCacheID 的实际用处应该是 shouldCache 吧？

2022-03-24 06:28 UTC, EliChen95 commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +const NODE_SHOULD_NOT_CACHE: SchemaNode['id'][] = ['dummyLoopContainer', 'placeholder-node'];
这两个类型的node没有渲染到dom tree，但是在渲染过程中用到了 useInstantiateProps 去解析 shouldRender或iterableState , 且path保持着当前node的path， 如果恰巧此时node的props是需要被cache的，会在解析这两个节点的时候重新setProps导致之前缓存的props变化

2022-03-24 08:45 UTC, markduan commented on packages/render-engine/src/boot-up/node-props-cache.ts
> +const NODE_SHOULD_NOT_CACHE: SchemaNode['id'][] = ['dummyLoopContainer', 'placeholder-node'];
好吧，先这样，后面再优化一下。

2022-03-31 09:23 UTC, markduan approved these changes

2022-03-31 09:24 UTC, merged