fix: solve the problem of browser security policy when svg loading starts
quanxiang-cloud/one-for-all pull request #38
Opened 2022-03-25 08:00 UTC by mingbing737

Use the fetch request sprite to insert the obtained dom under the corresponding icon

2022-03-28 03:05 UTC, markduan requested changes

2022-03-28 03:05 UTC, markduan commented on packages/example/src/icon-preview/previewIcon.tsx
> +    fetch('/pkg/icon/dist/@one-for-all/icon@0.5.0/svgNameMap.json')
每次改这里的版本都很费劲，为什么在构建的时候不把 svgNameMap 也输出一份到 latest 目录呢？

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/index.tsx
> +  'data-node-key'?: string;
'data-node-key' 这个 property 是用来做什么的？

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/index.tsx
> +    getIconInSprite.getIconById(svgSprite, name).then((icon) => {
1. 这个 use effect 需要加一个当前组件是否在 unmount 的判断
2. dataNodeKey 这个方式直接返回 string 就好了

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/index.tsx
> +  const [icon, setIcon] = useState('');
icon ? 请给一个更准确的变量名

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/index.tsx
> +      <use xlinkHref={`#${name}`} />
这个 use tag 是多余的吧？

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/index.tsx
> +        ></symbol>
替换 `></symbol>` 为 `/>`

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/getIconInSprite.ts
> +    if (!this.spriteMap[spriteUrl]) {
svg sprite 还有多个吗？为什么这里要定义成一个 map？是为了以后支持双色和彩色 icon？

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/getIconInSprite.ts
> +    return this.spriteMap[spriteUrl].querySelector(`#${CSS.escape(id)}`) as SVGSymbolElement;
这里有 bug 吧，第一次调用 getIconById 会走上面的 if block，然后 wait fetchSprite，但是第二次调用的时候会直接走 16 行，这个时候 fetchSprite 可能还没有 resolve 呢，你把 fetchSprite 延迟 5s 测试看看？

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/getIconInSprite.ts
> +  setSprite(key: string, value: string) {
你竟然自己实现了一个 public/subscribe 模式，额，过度了吧，这完全不是 singleton promise 啊

2022-03-28 03:05 UTC, markduan commented on packages/icon/src/getIconInSprite.ts
> +  setSprite(key: string, value: string) {
不要把简单的问题搞复杂

2022-03-28 09:52 UTC, markduan requested changes

2022-03-28 09:52 UTC, markduan commented on packages/icon/src/getIconInSprite.ts
> +    this.setSprite(await this.fetchSprite(spriteUrl));
不同的逻辑还是揉在了一起，看上去很乱，是不是应该这样：

1. getIconByID return promise<string>, 在 getIconByID 里判断是否有 return 最终 string 的 promise，有则 return
2. 如果没有，则新建一个 promise 去 svg sprite 以及取 symbol，对 getIconByID 来说，fetch svg 和取 symbol 的过程都是它不关心的

2022-03-28 09:52 UTC, markduan commented on packages/icon/src/getIconPathById.ts
> +  const sprite = await fetchSpritePromise;
这里用 css escape 有必要吗？

2022-03-28 09:52 UTC, markduan commented on packages/icon/src/getIconPathById.ts
> +  const spriteText = await(await fetch(svgSprite)).text();
不要用连着两个 await 这样吧，定义一个临时变量也不是不可以，或者换成 promise-then 的格式也可以。更重要的是 fetch 是会报错的，需要做一下错误处理

2022-03-28 09:52 UTC, markduan commented on packages/icon/src/getIconPathById.ts
> +  return spriteParent.children[0] as SVGAElement
直接 return 一个 div 也可以吧？再取 children 是为什么？或者在第 14 行为什么不直接 create 一个 svg element？

2022-03-28 10:10 UTC, mingbing737 commented on packages/icon/src/getIconPathById.ts
> +  const sprite = await fetchSpritePromise;
因为id有数字开头的，所以需要加上这个，否则会报错

2022-03-28 10:12 UTC, markduan commented on packages/icon/src/getIconPathById.ts
> +  const sprite = await fetchSpritePromise;
为什么不直接用 getElementById 呢？

2022-03-29 01:28 UTC, mingbing737 commented on packages/icon/src/getIconPathById.ts
> +  const sprite = await fetchSpritePromise;
这个方法是document的，普通的dom没有这个方法

2022-03-29 02:09 UTC, merged