refactor: Artery engine replace schema with artery and support node o…
quanxiang-cloud/one-for-all pull request #63
Opened 2022-04-24 11:10 UTC by nfwyst

1.  replace schema with artery
2. support node operation utils
3. support command

2022-04-24 11:19 UTC, markduan requested changes

2022-04-24 11:19 UTC, markduan commented on packages/artery-engine/config-json/constants.ts
> +export const PackageListKey = 'artery-design-package-list';
这些 json 配置文件应该放到各自的 package 中，然后在 qxp-web 组合

2022-04-25 13:46 UTC, markduan requested changes
packages/icon/config-json/icon-package-category-variants.json

这个文件你竟然直接提交上来了，不合适吧？想想这种文件应该如何维护？

2022-04-25 13:46 UTC, markduan commented on packages/artery-engine/config-json/index.ts
> +export const PackageListKey = 'artery-design-package-list';
这个文件应该放到 qxp-web 吧？

2022-04-25 13:46 UTC, markduan commented on packages/artery-engine/config-json/index.ts
> +export const PackageListKey = 'artery-design-package-list';
config-json 里的文件都不应该放到 artery-engine 中，他们和 artery-engine 都没关系，他们只是和 block 有关

2022-04-25 13:46 UTC, markduan commented on packages/artery-engine/package.json
> +    "@one-for-all/artery-utils": "~0.11.1"
没看到哪里有使用 artery-utils 的地方，这个依赖可以去掉吧

2022-04-25 13:46 UTC, markduan commented on packages/artery-engine/package.json
> +    "@one-for-all/artery-utils": "~0.11.1"
rtery-renderer 我也没找到有使用的地方

2022-04-25 13:46 UTC, markduan commented on packages/artery-engine/src/utils/index.ts
> +function getImportReactComponentNode<T>(): (node: ReactComponentNode) => Promise<ReactComponentNodeWithRender<T>>  {
这个方法哪个 block 会需要？

2022-04-25 13:46 UTC, markduan commented on packages/icon/config-json/index.ts
> +export const IconPackageCategoryVariantsKey = 'artery-design-package-category-variants:icon:0.6.1';
packages/icon/config-json/index.ts 和 packages/ui/config-json/index.ts 都不应该放到这里。package 提供 manifest/bundle/props-spec, 但是 package 不管这三份数据是如何存储的。

在这里 `key: 'artery-design-package-category-variants:icon:0.6.1',` 没有任何上下文，也不应该定义。

2022-04-26 05:35 UTC, nfwyst commented on packages/icon/config-json/index.ts
> +export const IconPackageCategoryVariantsKey = 'artery-design-package-category-variants:icon:0.6.1';
目前只是 mock, 并非最后的实现

2022-04-26 05:36 UTC, markduan commented on packages/icon/config-json/index.ts
> +export const IconPackageCategoryVariantsKey = 'artery-design-package-category-variants:icon:0.6.1';
mock 数据也不能写在这里

2022-04-26 06:42 UTC, merged